version: 2.0

workflows:
  ios:
    name: Build iOS App (without publishing)
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
      xcode: latest    # Ensure you're using the latest Xcode version
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get  # Install Flutter dependencies

      - name: Install Ruby 3.1.0 (or higher)
        script: |
          rbenv install 3.1.0
          rbenv global 3.1.0
          ruby -v  # Verify Ruby version

      - name: Clean Flutter project
        script: |
          flutter clean  # Clean Flutter build files
          flutter pub get  # Re-fetch Flutter dependencies

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods  # Install CocoaPods
          pod --version  # Verify CocoaPods installation

      - name: Clean CocoaPods cache
        script: |
          pod cache clean --all  # Clear CocoaPods cache
          pod repo update  # Update pod repositories

      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update --no-integrate  # Install iOS dependencies via CocoaPods, ensure repos are up-to-date
          cd ..  # Return to the root directory

      - name: Ensure Flutter plugin files
        script: |
          echo "Checking .flutter-plugins file"
          cat .flutter-plugins || echo "No .flutter-plugins file found"
          echo "Checking .flutter-plugins-dependencies file"
          cat .flutter-plugins-dependencies || echo "No .flutter-plugins-dependencies file found"

      - name: Build iOS App (without publishing)
        script: |
          flutter build ios --release --no-codesign  # Build iOS release app without code-signing
          # Archive the app using Xcode
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/ios/archive/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/iphoneos

    artifacts:
      - build/ios/iphoneos/Runner.ipa  # Specify .ipa output file (no publishing)

  android:
    name: Build and deploy to Play Store
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get  # Install Flutter dependencies

      - name: Build APK
        script: |
          flutter build apk --release  # Build APK for release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Specify APK output file
