version: 2.0

workflows:
  ios:
    name: Build and deploy to TestFlight
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
      xcode: latest    # Ensure you're using the latest Xcode version
    scripts:
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod repo update
      - name: Install Flutter dependencies
        script: flutter clean
                flutter pub get
                flutter build ios
      - name: Install iOS dependencies
        script: |
                cd ios
                pod install --repo-update
      # Removed Run tests script to skip test execution
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign   # Skip code-signing for now
          # Ensure correct build path for .ipa generation
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/ios/archive/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/iphoneos
    artifacts:
      - build/ios/iphoneos/Runner.ipa  # Make sure to specify .ipa output file

  android:
    name: Build and deploy to Play Store
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      # Removed Run tests script to skip test execution
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

# Custom environment configuration (optional)
environment:
  flutter: stable  # Use the stable version by default (Codemagic does this automatically)
  # Additional environment variables can be added if necessary
