version: 2.0

workflows:
  ios:
    name: Build and deploy to TestFlight
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
      xcode: latest    # Ensure you're using the latest Xcode version
    scripts:
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod repo update
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS App
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app

  android:
    name: Build and deploy to Play Store
    environment:
      flutter: stable  # Codemagic automatically uses the stable version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

# Custom environment configuration (optional)
environment:
  flutter: stable  # Use the stable version by default (Codemagic does this automatically)
  # Additional environment variables can be added if necessary
