platform :ios, '12.0'

# Ensure that your flutter SDK path is correctly set
flutter_application_path = '../'

# Flutter automatically handles loading plugin dependencies
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Flutter', :path => flutter_application_path
  pod 'FlutterPluginRegistrant', :path => File.join(flutter_application_path, 'packages', 'flutter_plugin_registrant')

  # Add your other dependencies here
end
